/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**  @author Denis */


import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class CarnetDadresses extends javax.swing.JFrame {

    /**     * Creates new form CarnetDadresses */
    public CarnetDadresses() throws IOException {
        initComponents();
        
        // La fenêtre de dialogue de saisie est créée et positionnée sur boiteGlobale
        saisieDialog=new Saisie(boiteGlobale,true);
        // La boite de dialogue est positionnée relativement à la fenêtre principale (boiteGlobale)
        saisieDialog.setLocationRelativeTo(boiteGlobale);

        setIcon();
        // Initialiser les contacts
        initContacts();
    }

    private void setIcon() {
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/photo0.png")));
    }
    
    private void initContacts() throws IOException{
        Dimension taille;
        String ligne;
        String [] infoContact=new String[13];
        contacts=new Contact[50];
        FichierAdresses fich=new FichierAdresses();
        if (fich.ouvrirEnLecture("../donnees/listeContacts.txt")){
        int i=0;
      
        do {
            ligne=fich.lire();
            infoContact=fich.extraireDonnees(ligne);
            
            if (ligne!=null){
                contacts[i]=new Contact(infoContact,i) ;
                taille=contacts[i].getPreferredSize();
                contacts[i].setBounds(0, (taille.height+5)*i, taille.width, taille.height);
                boiteContacts.add(contacts[i]);

                taille.setSize(taille.width, (i+1)*(taille.height+5));
                boiteContacts.setPreferredSize(taille); 
                boiteContacts.validate();
                
                // Créer un écouteur d'événement sur un contact
                contacts[i].addMouseListener(new java.awt.event.MouseAdapter() {
                   @Override
                   public void mouseReleased(java.awt.event.MouseEvent evt){
                       contactMouseReleased(evt);
                   }
                });
                
                i++;
            }
        } while (ligne!=null);
        
        contacts[numero].setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 0), 5));

        Infos contactInfos=new Infos(contacts[numero].getListeInfos());
        Dimension tailleContactInfos=contactInfos.getPreferredSize();
        contactInfos.setBounds(18, 30, tailleContactInfos.width, tailleContactInfos.height);
        boiteInfos.add(contactInfos);
        boiteInfos.validate();
        }
    }
    
    private void contactMouseReleased(java.awt.event.MouseEvent evt){

        boiteInfos.removeAll();
        boiteInfos.validate();

        Contact contactClique=(Contact) evt.getSource();
        numero = contactClique.getId() ;
        
        // Créer un cadre de sélection
        contacts[numeroPrecedent].setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        contacts[numero].setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 0), 5));
        numeroPrecedent=numero;
        
        Infos contactInfos=new Infos(contacts[numero].getListeInfos());
        Dimension tailleContactInfos=contactInfos.getPreferredSize();
        contactInfos.setBounds(18, 30, tailleContactInfos.width, tailleContactInfos.height);
        boiteInfos.add(contactInfos);
        boiteInfos.repaint();
        boiteInfos.validate();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boiteGlobale = new javax.swing.JPanel();
        boiteAvecBarreDefilement = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        boiteContacts = new javax.swing.JPanel();
        boiteInfos = new javax.swing.JPanel();
        plusBtn = new javax.swing.JButton();
        moinsBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Carnet d'adresses");
        setIconImages(null);

        boiteGlobale.setPreferredSize(new java.awt.Dimension(950, 700));
        boiteGlobale.setLayout(new java.awt.GridLayout(1, 2, 50, 50));

        boiteAvecBarreDefilement.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Liste des contacts", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        boiteAvecBarreDefilement.setPreferredSize(new java.awt.Dimension(450, 500));
        boiteAvecBarreDefilement.setRequestFocusEnabled(false);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(32767, 100));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(100, 50));

        javax.swing.GroupLayout boiteContactsLayout = new javax.swing.GroupLayout(boiteContacts);
        boiteContacts.setLayout(boiteContactsLayout);
        boiteContactsLayout.setHorizontalGroup(
            boiteContactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );
        boiteContactsLayout.setVerticalGroup(
            boiteContactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 653, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(boiteContacts);

        javax.swing.GroupLayout boiteAvecBarreDefilementLayout = new javax.swing.GroupLayout(boiteAvecBarreDefilement);
        boiteAvecBarreDefilement.setLayout(boiteAvecBarreDefilementLayout);
        boiteAvecBarreDefilementLayout.setHorizontalGroup(
            boiteAvecBarreDefilementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
        );
        boiteAvecBarreDefilementLayout.setVerticalGroup(
            boiteAvecBarreDefilementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boiteAvecBarreDefilementLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        boiteGlobale.add(boiteAvecBarreDefilement);

        boiteInfos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Infos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        boiteInfos.setPreferredSize(new java.awt.Dimension(450, 500));

        javax.swing.GroupLayout boiteInfosLayout = new javax.swing.GroupLayout(boiteInfos);
        boiteInfos.setLayout(boiteInfosLayout);
        boiteInfosLayout.setHorizontalGroup(
            boiteInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );
        boiteInfosLayout.setVerticalGroup(
            boiteInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        boiteGlobale.add(boiteInfos);

        plusBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plusBtn.setText("+");
        plusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusBtnActionPerformed(evt);
            }
        });

        moinsBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        moinsBtn.setText("-");
        moinsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moinsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(boiteGlobale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(plusBtn)
                .addGap(159, 159, 159)
                .addComponent(moinsBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(boiteGlobale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plusBtn)
                    .addComponent(moinsBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void plusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusBtnActionPerformed

        // La boite de dialogue est affichée
        saisieDialog.setVisible(true);
        if (saisieDialog.getListeContacts()!=null){
            boiteContacts.removeAll();
            boiteInfos.removeAll();
            numero=saisieDialog.getListeContacts().size()-1;
            numeroPrecedent=numero;
            try {
                initContacts();
            } catch (IOException ex) {
                Logger.getLogger(CarnetDadresses.class.getName()).log(Level.SEVERE, null, ex);
            }
            boiteContacts.validate();
        }
    }//GEN-LAST:event_plusBtnActionPerformed

    private void moinsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moinsBtnActionPerformed
        try {
            saisieDialog.supprimer(numero);
        } catch (IOException ex) {
            Logger.getLogger(CarnetDadresses.class.getName()).log(Level.SEVERE, null, ex);
        }
        boiteContacts.removeAll();
        boiteInfos.removeAll();
        //boiteContacts.repaint();
        numero=Math.max(numero-1, 0);
        numeroPrecedent=numero;
        try {
            initContacts();
        } catch (IOException ex) {
            Logger.getLogger(CarnetDadresses.class.getName()).log(Level.SEVERE, null, ex);
        }
        boiteContacts.validate();
    }//GEN-LAST:event_moinsBtnActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarnetDadresses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarnetDadresses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarnetDadresses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarnetDadresses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CarnetDadresses().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(CarnetDadresses.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    private Contact [] contacts;
    private int numero=0;
    private int numeroPrecedent=0;
    private Saisie saisieDialog;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boiteAvecBarreDefilement;
    private javax.swing.JPanel boiteContacts;
    private javax.swing.JPanel boiteGlobale;
    private javax.swing.JPanel boiteInfos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton moinsBtn;
    private javax.swing.JButton plusBtn;
    // End of variables declaration//GEN-END:variables
}
