import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class Infos extends javax.swing.JPanel {

    public Infos(String [] inf)  {
        initComponents();
        setVisible(true);

        try{
            setNom(inf[0]);
            setPrenom(inf[1]);
            setPhoto( inf[2]);
            setProfession(inf[3]);
            setEntreprise(inf[4]);
            setNumPro(inf[5]);
            setNumCel(inf[6]);
            setNumDom(inf[7]);
            setCourriel(inf[8]);
            setRue(inf[9]);
            setCodePostal(inf[10]);
            setVille(inf[11]);
            setPays(inf[12]);
        }
        catch(java.lang.ArrayIndexOutOfBoundsException e){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        photoLbl = new javax.swing.JLabel();
        prenomLbl = new javax.swing.JLabel();
        nomLbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        professionLbl = new javax.swing.JLabel();
        entrepriseLbl = new javax.swing.JLabel();
        courrielLbl = new javax.swing.JLabel();
        numProLbl = new javax.swing.JLabel();
        numCelLbl = new javax.swing.JLabel();
        numDomLbl = new javax.swing.JLabel();
        proLbl = new javax.swing.JLabel();
        celLbl = new javax.swing.JLabel();
        domLbl = new javax.swing.JLabel();
        rueLbl = new javax.swing.JLabel();
        codePostalLbl = new javax.swing.JLabel();
        villeLbl = new javax.swing.JLabel();
        paysLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 153));
        setMaximumSize(new java.awt.Dimension(600, 200));
        setMinimumSize(new java.awt.Dimension(50, 50));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(380, 500));
        setRequestFocusEnabled(false);

        prenomLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        prenomLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        nomLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nomLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        professionLbl.setText(" ");
        professionLbl.setPreferredSize(new java.awt.Dimension(356, 16));

        entrepriseLbl.setText(" ");
        entrepriseLbl.setPreferredSize(new java.awt.Dimension(356, 16));

        courrielLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        courrielLbl.setText(" ");
        courrielLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        courrielLbl.setPreferredSize(new java.awt.Dimension(356, 16));

        numProLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        numProLbl.setText(" ");

        numCelLbl.setText(" ");

        numDomLbl.setText(" ");

        proLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        proLbl.setText("(professionnel)");
        proLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        celLbl.setText("(cellulaire)");

        domLbl.setText("(domicile)");

        rueLbl.setText(" ");

        codePostalLbl.setText(" ");

        villeLbl.setText(" ");

        paysLbl.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(photoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(prenomLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(numProLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numCelLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numDomLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(proLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(celLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(domLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paysLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rueLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(codePostalLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(villeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(professionLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entrepriseLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(courrielLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(photoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(prenomLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nomLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(professionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(entrepriseLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(courrielLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(proLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numProLbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numCelLbl)
                    .addComponent(celLbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(domLbl)
                    .addComponent(numDomLbl))
                .addGap(43, 43, 43)
                .addComponent(rueLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codePostalLbl)
                    .addComponent(villeLbl))
                .addGap(10, 10, 10)
                .addComponent(paysLbl)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel celLbl;
    private javax.swing.JLabel codePostalLbl;
    private javax.swing.JLabel courrielLbl;
    private javax.swing.JLabel domLbl;
    private javax.swing.JLabel entrepriseLbl;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nomLbl;
    private javax.swing.JLabel numCelLbl;
    private javax.swing.JLabel numDomLbl;
    private javax.swing.JLabel numProLbl;
    private javax.swing.JLabel paysLbl;
    private javax.swing.JLabel photoLbl;
    private javax.swing.JLabel prenomLbl;
    private javax.swing.JLabel proLbl;
    private javax.swing.JLabel professionLbl;
    private javax.swing.JLabel rueLbl;
    private javax.swing.JLabel villeLbl;
    // End of variables declaration//GEN-END:variables


    public javax.swing.JLabel getNomLbl() {
        return nomLbl;
    }

    public void setNom(String txtTmp) {
        nomLbl.setText(txtTmp);
    }

    public void setPrenom(String txtTmp) {
        prenomLbl.setText(txtTmp);
    }

    public javax.swing.JLabel getPhotoLbl() {
        return photoLbl;
    }

    public void setPhoto(String txtTmp) throws NullPointerException {
        // Créer une icône
        ImageIcon iconPhoto;
            if (txtTmp.equals("/images/photo0.png") ||txtTmp.equals("null")) {
                java.net.URL imageURL = CarnetDadresses.class.getResource("/images/photo0.png");
                iconPhoto = new ImageIcon(imageURL);
            }
            else {
                String imageURL=txtTmp ;
                iconPhoto = new ImageIcon(imageURL);
            }
        
        java.awt.Image imagePhoto=iconPhoto.getImage();
        imagePhoto=imagePhoto.getScaledInstance(-114, 114,java.awt.Image.SCALE_SMOOTH);
        iconPhoto.setImage(imagePhoto);
        photoLbl.setIcon(iconPhoto);
    }

    public javax.swing.JLabel getCourrielLbl() {
        return courrielLbl;
    }

    public void setCourriel(String txtTmp) {
        courrielLbl.setText(txtTmp);
    }

    public javax.swing.JLabel getEntrepriseLbl() {
        return entrepriseLbl;
    }

    public void setEntreprise(String txtTmp) {
        entrepriseLbl.setText(txtTmp);
    }

    public javax.swing.JLabel getNumCelLbl() {
        return numCelLbl;
    }

    public void setNumCel(String txtTmp) {
        numCelLbl.setText(txtTmp);
    }

    public javax.swing.JLabel getNumDomLbl() {
        return numDomLbl;
    }

    public void setNumDom(String txtTmp) {
        numDomLbl.setText(txtTmp);
    }

    public javax.swing.JLabel getNumProLbl() {
        return numProLbl;
    }

    public void setNumPro(String txtTmp) {
        numProLbl.setText(txtTmp);
    }

    public javax.swing.JLabel getPrenomLbl() {
        return prenomLbl;
    }

    public javax.swing.JLabel getProfessionLbl() {
        return professionLbl;
    }

    public void setProfession(String txtTmp) {
        professionLbl.setText(txtTmp);
    }

    public javax.swing.JLabel getRueLbl() {
        return rueLbl;
    }

    public void setRue(String txtTmp) {
        rueLbl.setText(txtTmp);
    }

    public JLabel getCodePostalLbl() {
        return codePostalLbl;
    }

    public void setCodePostal(String txtTmp) {
        codePostalLbl.setText(txtTmp);
    }
    
    public javax.swing.JLabel getVilleLbl() {
        return villeLbl;
    }

    public void setVille(String txtTmp) {
        villeLbl.setText(txtTmp);
    }

    public javax.swing.JLabel getPaysLbl() {
        return paysLbl;
    }

    public void setPays(String txtTmp) {
        paysLbl.setText(txtTmp);
    }

}
