/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author Denis
 */
public class Saisie extends javax.swing.JDialog {

    /**
     * Creates new form Saisie
     */
    public Saisie(javax.swing.JPanel parent, boolean modal) {
        //super(parent, modal);
        initComponents();
        // Installer une icone dans la barre de titre pour cette fenêtre et la celle de dialogue
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/photo0.png")));
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        photoLbl = new javax.swing.JLabel();
        nomTfd = new javax.swing.JTextField();
        prenomTfd = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        telephonesLbl = new javax.swing.JLabel();
        professionnelTfd = new javax.swing.JLabel();
        cellulaireLbl = new javax.swing.JLabel();
        domicileLbl = new javax.swing.JLabel();
        numProTfd = new javax.swing.JTextField();
        numCelTfd = new javax.swing.JTextField();
        numDomTfd = new javax.swing.JTextField();
        courrielLbl = new javax.swing.JLabel();
        courrielTfd = new javax.swing.JTextField();
        adresseLbl = new javax.swing.JLabel();
        rueTfd = new javax.swing.JTextField();
        villeTfd = new javax.swing.JTextField();
        codePostalTfd = new javax.swing.JTextField();
        paysTfd = new javax.swing.JTextField();
        professionLbl = new javax.swing.JLabel();
        professionTfd = new javax.swing.JTextField();
        entrepriseLbl = new javax.swing.JLabel();
        entrepriseTfd1 = new javax.swing.JTextField();
        validerBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        photoLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        photoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/modifier.png"))); // NOI18N
        photoLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                photoLblMouseReleased(evt);
            }
        });

        nomTfd.setText("nom");

        prenomTfd.setText("prénom"); // NOI18N
        prenomTfd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenomTfdActionPerformed(evt);
            }
        });

        telephonesLbl.setText("Téléphones");

        professionnelTfd.setForeground(new java.awt.Color(102, 102, 102));
        professionnelTfd.setText("professionnel");

        cellulaireLbl.setForeground(new java.awt.Color(102, 102, 102));
        cellulaireLbl.setText("cellulaire");

        domicileLbl.setForeground(new java.awt.Color(102, 102, 102));
        domicileLbl.setText("domicile");

        numProTfd.setText("numéro");
        numProTfd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numProTfdActionPerformed(evt);
            }
        });

        numCelTfd.setText("numéro");
        numCelTfd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numCelTfdActionPerformed(evt);
            }
        });

        numDomTfd.setText("numéro");
        numDomTfd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numDomTfdActionPerformed(evt);
            }
        });

        courrielLbl.setText("Courriel");

        courrielTfd.setText("prenom.nom@message.com"); // NOI18N

        adresseLbl.setText("Adresse");

        rueTfd.setText("numéro et nom de la voie"); // NOI18N
        rueTfd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rueTfdActionPerformed(evt);
            }
        });

        villeTfd.setText("ville"); // NOI18N
        villeTfd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                villeTfdActionPerformed(evt);
            }
        });

        codePostalTfd.setText("code postal"); // NOI18N
        codePostalTfd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codePostalTfdActionPerformed(evt);
            }
        });

        paysTfd.setText("pays"); // NOI18N
        paysTfd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paysTfdActionPerformed(evt);
            }
        });

        professionLbl.setText("Profession");

        professionTfd.setText("profession");
        professionTfd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                professionTfdActionPerformed(evt);
            }
        });

        entrepriseLbl.setText("Entreprise");

        entrepriseTfd1.setText("entreprise");
        entrepriseTfd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrepriseTfd1ActionPerformed(evt);
            }
        });

        validerBtn.setText("Valider");
        validerBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        validerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(professionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(22, 22, 22)
                            .addComponent(professionTfd))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(entrepriseLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(22, 22, 22)
                            .addComponent(entrepriseTfd1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(photoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nomTfd)
                                    .addComponent(prenomTfd, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(professionnelTfd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(telephonesLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(domicileLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cellulaireLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(courrielLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(adresseLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(codePostalTfd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(villeTfd))
                                .addComponent(numDomTfd)
                                .addComponent(numProTfd, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(numCelTfd)
                                .addComponent(rueTfd)
                                .addComponent(courrielTfd)
                                .addComponent(paysTfd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(validerBtn)
                        .addGap(150, 150, 150)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(photoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nomTfd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(prenomTfd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(professionLbl)
                    .addComponent(professionTfd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entrepriseLbl)
                    .addComponent(entrepriseTfd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(telephonesLbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(professionnelTfd)
                    .addComponent(numProTfd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cellulaireLbl)
                    .addComponent(numCelTfd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(domicileLbl)
                    .addComponent(numDomTfd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courrielLbl)
                    .addComponent(courrielTfd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adresseLbl)
                    .addComponent(rueTfd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(villeTfd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codePostalTfd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paysTfd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(validerBtn)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prenomTfdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenomTfdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prenomTfdActionPerformed

    private void numProTfdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numProTfdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numProTfdActionPerformed

    private void numCelTfdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numCelTfdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numCelTfdActionPerformed

    private void numDomTfdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numDomTfdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numDomTfdActionPerformed

    private void rueTfdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rueTfdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rueTfdActionPerformed

    private void villeTfdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_villeTfdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_villeTfdActionPerformed

    private void codePostalTfdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codePostalTfdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codePostalTfdActionPerformed

    private void paysTfdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paysTfdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paysTfdActionPerformed

    private void professionTfdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_professionTfdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_professionTfdActionPerformed

    private void entrepriseTfd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrepriseTfd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entrepriseTfd1ActionPerformed


    private void photoLblMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_photoLblMouseReleased
        // Créer un objet de type File
        File fichierPhoto=null;
        // Créer un composant JFileChooser
        JFileChooser fichierArechercher=new JFileChooser(fichierPhoto);
        // Ouvrir une boite de dialogue qui permet la recherche du fichier
        int etatRetour=fichierArechercher.showOpenDialog(Saisie.this);
       
        if (etatRetour==JFileChooser.APPROVE_OPTION){
            // Récupérer le fichier sélectionné
            fichierPhoto=fichierArechercher.getSelectedFile();
            // Stocker le chemin d'accès
            String url = fichierPhoto.toString();
            // Afficher la photo
            setPhoto(url);
        }
    }//GEN-LAST:event_photoLblMouseReleased

    private void setDonnees(){
        setNom( nomTfd.getText());
        setPrenom( prenomTfd.getText());
        setProfession( professionTfd.getText());
        setNumPro( numProTfd.getText());
        setNumCel( numCelTfd.getText());
        setNumDom( numDomTfd.getText());
        setCourriel( courrielTfd.getText());
        setRue( rueTfd.getText());
        setCodePostal( codePostalTfd.getText());
        setVille( villeTfd.getText());
        setPays( paysTfd.getText());
    }
    
    private void validerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerBtnActionPerformed
        setDonnees();
        String infos=nom+";"+prenom+";"+photo+";"+profession+";"+entreprise+";"+numPro+";"+numCel+";"+numDom+";"+rue+";"+codePostal+";"+ville+";"+pays ;
        try {
            ecrireLeContact(infos);
        } catch (IOException ex) {
            Logger.getLogger(Saisie.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_validerBtnActionPerformed

    private void ecrireLeContact(String tmptxt) throws IOException{
        // Lire le fichier listeContacts.txt et mémoriser le contenu dans une liste
        lireLesContacts();
        // Enregistrer le nouveau contact à la fin de la liste
        listeContacts.add(tmptxt);
        // Ecrire l'intégralité de la liste dans le fichier listeContacts.txt
        ecrireLesContacts();
    }

    public void supprimer(int tmpnum) throws IOException{
        // Lire le fichier listeContacts.txt et mémoriser le contenu dans une liste
        lireLesContacts();
        // Supprimer le contact positionné à l'indice tmpnum
        listeContacts.remove(tmpnum);
        // Ecrire l'intégralité de la liste dans le fichier listeContacts.txt
        ecrireLesContacts();
    }

    private void ecrireLesContacts() throws IOException{
         FichierAdresses f=new FichierAdresses();
         f.ouvrirEnEcriture("../donnees/listeContacts.txt");
         for (Object e : listeContacts){
             f.ecrire((String) e);
         }
         f.fermer();
    }
    
    private void lireLesContacts() throws IOException{
        listeContacts=new ArrayList();
        FichierAdresses f=new FichierAdresses();
        f.ouvrirEnLecture("../donnees/listeContacts.txt");
        String chaine= null;
        do{
            chaine=f.lire();
            if (chaine!=null) listeContacts.add(chaine);
        }
        while(chaine!=null);
        f.fermer();
    }
    
    // Récupérer les données mise à jour
    //public boolean getDonnees(){
    //    return true;
    //}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Saisie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Saisie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Saisie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Saisie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            Saisie dialog = new Saisie(new javax.swing.JPanel(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    
    private ArrayList listeContacts;
    private String nom, prenom, profession, entreprise, numPro, numDom, numCel, courriel, rue, codePostal, ville, pays ;
    private String photo="/images/photo0.png";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adresseLbl;
    private javax.swing.JLabel cellulaireLbl;
    private javax.swing.JTextField codePostalTfd;
    private javax.swing.JLabel courrielLbl;
    private javax.swing.JTextField courrielTfd;
    private javax.swing.JLabel domicileLbl;
    private javax.swing.JLabel entrepriseLbl;
    private javax.swing.JTextField entrepriseTfd1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nomTfd;
    private javax.swing.JTextField numCelTfd;
    private javax.swing.JTextField numDomTfd;
    private javax.swing.JTextField numProTfd;
    private javax.swing.JTextField paysTfd;
    private javax.swing.JLabel photoLbl;
    private javax.swing.JTextField prenomTfd;
    private javax.swing.JLabel professionLbl;
    private javax.swing.JTextField professionTfd;
    private javax.swing.JLabel professionnelTfd;
    private javax.swing.JTextField rueTfd;
    private javax.swing.JLabel telephonesLbl;
    private javax.swing.JButton validerBtn;
    private javax.swing.JTextField villeTfd;
    // End of variables declaration//GEN-END:variables

    public void setNom(String nom) {
        this.nom = nom;
    }

    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    public void setPhoto(String photo) {
        ImageIcon iconPhoto=new ImageIcon(photo);
        java.awt.Image imagePhoto=iconPhoto.getImage();
        imagePhoto=imagePhoto.getScaledInstance(-50, 50,java.awt.Image.SCALE_SMOOTH);
        iconPhoto.setImage(imagePhoto);
        photoLbl.setIcon(iconPhoto);
        this.photo = photo;
    }

    public void setProfession(String profession) {
        this.profession = profession;
    }

    public void setEntreprise(String entreprise) {
        this.entreprise = entreprise;
    }

    public void setNumPro(String numPro) {
        this.numPro = numPro;
    }

    public void setNumDom(String numDom) {
        this.numDom = numDom;
    }

    public void setNumCel(String numCel) {
        this.numCel = numCel;
    }

    public void setCourriel(String courriel) {
        this.courriel = courriel;
    }

    public void setRue(String rue) {
        this.rue = rue;
    }

    public void setCodePostal(String codePostal) {
        this.codePostal = codePostal;
    }

    public void setVille(String ville) {
        this.ville = ville;
    }

    public void setPays(String pays) {
        this.pays = pays;
    }

    public ArrayList getListeContacts() {
        return listeContacts;
    }
}
